### ISSUE TITLE
some questions about CIMS.pl

### ISSUE THREAD

**Issue by kir1to455** [chaolinzhanglab/czplib#3]
Hello,when I use CIMS.pl to get the sites, it will have some following problems.
'Inconsistency detected between the tag file and the mutation file. Make sure the NAME column of the two files use the same IDs'
I don't know how to solve it, can you give me some advice?
Here is my command:
perl CIMS.pl -v -n 5 -p -c ./cache_del --keep-cache Mettle3.WT.total.tag.uniq.bed Mettle3.WT.total.tag.uniq.del.bed Mettle3.WT.total.tag.uniq.del.CIMS.txt
Mettle3.WT.total.tag.uniq.bed comes from "cat Mettle3.WT.rep1.tag.uniq.bed Mettle3.WT.rep2.tag.uniq.bed > Mettle3.WT.total.tag.uniq.bed"

**Comment by zhangchaolin** [comment]
One common problem that causes this issue is that the tag IDs in the tag bed file is not unique.

**Comment by kir1to455** [comment]
> One common problem that causes this issue is that the tag IDs in the tag bed file is not unique.
Hello, I try to reuse tag2collapse.pl to get the new $.tag.uniq.bed. But when I use CIMS.pl again, I got the following mistakes again:
"Inconsistency detected between the tag file and the mutation file. Make sure the NAME column of the two files use the same IDs"

**Comment by kir1to455** [comment]
Thanks for your help, the above problems have been successfully solved. However, there are new problems with the cims.pl runtime. ↓
"perl /ctk-1.1.4/simulateCIMS.pl -n 545573 -w 1  -p ./cache_C2T/mutation.pos.txt  -srand 1.17082803610629 Mettle3.WT.total.tag.uniq.bed ./cache_C2T/mutation.random.0.bed
position < 0?
 at /ctk-1.1.4/simulateCIMS.pl line 66, <$fin> line 265774.
CMD=perl /ctk-1.1.4/simulateCIMS.pl -n 545573 -w 1  -p ./cache_C2T/mutation.pos.txt  -srand 1.17082803610629 Mettle3.WT.total.tag.uniq.bed ./cache_C2T/mutation.random.0.bed failed: 6400"
Could you give me some advice and suggestions?
